apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: test-api
  namespace: apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: test-api
    #apps.tanzu.vmware.com/has-tests: "true"
    tanzu.app.live.view: "true"
spec:
  build:
    env:
      - name: BP_DOTNET_PROJECT_PATH
        value: "./test-api"
  # source:
  #   git:
  #     url: git-source-url
  #     ref:
  #       branch: git-branch-name